apiVersion: v1
kind: Service
metadata:
  namespace: group-5-ex
  name: week-9-tcc231017
  labels:
    app: week-9-tcc231017
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: week-9-tcc231017
